version: "3.1"

networks:
  pg-network:
    external: true

services:
  scheduler:
    networks:
      - pg-network
    volumes:
      - ".:/usr/local/airflow:rw"
  
  postgres:
    networks:
      - pg-network
  
  webserver:
    networks:
      - pg-network